from . import inherit_company
from . import inherit_settings
from . import inherit_partner
from . import inherit_crm
from . import inherit_product
from . import inherit_activity
from . import inherit_notes
from . import inherit_product_pricelist
from . import inherit_mail_activity_type
from . import inherit_crm_stage